# This is a basic workflow that is manually triggered

name: Nix build

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
  push:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@V27
    - uses: cachix/cachix-action@v15
      with:
        name: mrcjkb
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: build 
      run: nix flake check -L
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@V27
    - uses: cachix/cachix-action@v15
      with:
        name: mrcjkb
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: build 
      run: nix build -L
